### ISSUE TITLE
All content should record who created it

### ISSUE THREAD

**Issue by cdecinkoKnight** [Uintra/Uintra#33] opened 2019-02-08 21:38 UTC
Bulletins do not have an owner to identify who posted it.

**Comment by UintraContact** [comment] 2019-02-09 09:15
hi @cdecinkoKnight as i can see on our demo instance https://www.screencast.com/t/bkqH9f2bZ there is owner for bulletins. do you have some another result?

**Comment by UintraContact** [comment] 2019-02-09 09:16
same for news and other activities https://www.screencast.com/t/ocV1JcHb

where you can see content without owner?

**Comment by UintraContact** [comment] 2019-03-11 09:37
Hi @cdecinkoKnight as we were not able to reproduce this issue on our QA environment, neither on demo instance https://demo.uintra.com/login?ReturnUrl=%2f we close this tas for now. please, add new task with details, if you still have this problem and it is not something, you can see depended on your local environment

Br, Uintra team

**Closed by UintraContact** 2019-03-11 09:37 UTC
